name: 'Build'

on: [push, pull_request, merge_group]

env:
  CI: true

jobs:
  prepare:
    name: 'Install dependencies'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '18.x'
      - run: pnpm install

  typecheck:
    needs: [prepare]
    name: 'Typecheck'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '18.x'
      - run: pnpm install
      - run: pnpm run typecheck

  linting:
    needs: [prepare]
    name: 'ESLint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '18.x'
      - run: pnpm install
      - run: pnpm run lint --max-warnings=0

  prettier:
    needs: [prepare]
    name: 'Prettier'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '18.x'
      - run: pnpm install
      - run: pnpm exec prettier . --check

  test-interface:
    needs: [prepare]
    # This should actually include anything but parser and integration tests
    name: 'Interface tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '18.x'
      - run: pnpm install
      - run: pnpm run test:interface --runInBand

  test-parser:
    needs: [prepare]
    name: 'Parser tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '18.x'
      - run: pnpm install
      - run: pnpm run test:parser --runInBand

  test-integration:
    needs: [prepare]
    name: 'Integration tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '18.x'
      - run: pnpm install
      - run: pnpm run test:integration --runInBand

  build:
    needs: [prepare]
    name: 'Build'
    runs-on: ubuntu-latest
    if: github.repository == 'wowanalyzer/wowanalyzer'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '18.x'
      - run: pnpm install
      - name: Extract messages
        if: github.event_name != 'pull_request' && github.repository == 'wowanalyzer/wowanalyzer'
        run: pnpm run extract
      - name: Compile Lingui
        run: pnpm exec lingui compile
      - name: Calculate environment name
        id: environment-name
        run: echo "environment_name=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - name: Production build
        run: pnpm run build
        env:
          DISABLE_AUTOMATIC_ESLINT: true
          REACT_APP_ENABLE_GA: true
          REACT_APP_ENVIRONMENT_NAME: ${{ steps.environment-name.outputs.environment_name }}
          REACT_APP_VERSION: ${{ github.sha }}
      - run: tar -czf build.tar.gz build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.tar.gz

  e2e-build:
    needs: [prepare]
    name: 'e2e-build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '18.x'
      - run: pnpm install
      - name: Extract messages
        if: github.event_name != 'pull_request' && github.repository == 'wowanalyzer/wowanalyzer'
        run: pnpm run extract
      - name: Compile Lingui
        run: pnpm exec lingui compile
      - name: Calculate environment name
        id: environment-name
        run: echo "environment_name=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - name: Customize production environment variables
        # Even though this is a "production" build, it's actually a "development" build we're
        # using for e2e testing.
        run: cp .env.development .env.production
      - name: Production build
        run: pnpm run build
        env:
          DISABLE_AUTOMATIC_ESLINT: true
          REACT_APP_ENABLE_GA: false
          REACT_APP_ENVIRONMENT_NAME: ${{ steps.environment-name.outputs.environment_name }}
          REACT_APP_VERSION: ${{ github.sha }}
      - run: tar -czf build.tar.gz build
      - uses: actions/upload-artifact@v3
        with:
          name: e2e-build
          path: build.tar.gz

  e2e-test:
    needs: [e2e-build]
    name: e2e-test-shard-${{ matrix.shard }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '18.x'
      - run: pnpm install
      - uses: actions/download-artifact@v3
        with:
          name: e2e-build
      - run: tar -xzf build.tar.gz
      - name: Install Playwright deps
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm run e2e --shard=${{ matrix.shard }}/4
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-shard-${{ matrix.shard }}
          path: playwright-report/
          retention-days: 30

  # This only runs on PRs since it's not a part of the build step. This is
  # required as mistakes in i18n tags may trigger errors, and we skip the
  # extraction in the build for performance in PRs.
  extract-verify:
    needs: [prepare]
    name: 'Verify i18n messages'
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '18.x'
      - run: pnpm install
      - name: Extract messages
        run: pnpm run extract
      - name: Compile messages
        run: pnpm exec lingui compile

  docker-image:
    needs:
      [typecheck, linting, prettier, test-interface, test-parser, test-integration, e2e-test, build]
    name: 'Publish Docker image'
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' && github.repository == 'wowanalyzer/wowanalyzer' && !contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v1
        with:
          name: build
          path: .
      - run: tar -xzf build.tar.gz
      # Remove files we no longer need to speed up sending context to Docker
      - run: rm build.tar.gz
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: wowanalyzer/wowanalyzer
          tag-sha: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: 'Build martijnhols/healfie:${{env.DOCKER_BUILD_TAG}}'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  require-changelog-entry:
    name: 'Has new changelog entry'
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --no-tags --depth=1 origin $GITHUB_BASE_REF:$GITHUB_BASE_REF
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '18.x'
      - run: pnpm install
      - run: node scripts/require-changelog-entry.js
